kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-pod
          image: 722377226063.dkr.ecr.eu-central-1.amazonaws.com/ah-frontend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - port: 80
  selector:
    app: frontend