apiVersion: xrdgroup.org/v1alpha1
kind: ClusterXR
metadata:
  name: ah-app-eks-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  nodeRoleName: ah-app-node-role
  clusterRoleName: ah-app-cluster-role
  clusterName: ah-app-eks
  vpcName: ah-app-vpc
  securityGroupName: ah-app-security-group
  subnetName: ah-app-subnet
  albRoleName: ah-app-alb-role
  ebsCsiRoleName: ah-app-ebs-csi-role