apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: infrastructure_cluster/argocd/bottom_level_applications/application_infrastructure
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true