apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-cluster-configuration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: application_cluster/kubernetes/additional_resources
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: infrastructure_cluster/argocd/bottom_level_applications/application_cluster_configuration
  destination:
    name: arn:aws:eks:eu-central-1:722377226063:cluster/ah-app-eks
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true