stages:
    - validate
    - plan
    - apply 

before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate
  rules:
    - changes:
      - infrastructure_cluster/terraform/**/*
  tags:
    - ci-shared

plan:
  stage: plan
  script:
    - terraform plan -lock=false
  rules:
    - changes:
      - infrastructure_cluster/terraform/**/*
  tags:
    - ci-shared

apply:
  stage: apply
  script:
    - terraform apply --auto-approve
  when: manual
  rules:
    - changes:
      - infrastructure_cluster/terraform/**/*
  tags:
    - ci-shared
