stages:
  # - validation
  - build

# validation:
#   stage: validation
#   script:
#     - echo "Valid"
#   tags:
#     - ci-shared

before_script:
  - echo "validation"

build-frontend-image:
  stage: build
  image: docker:latest
  services:
      - docker:dind
  script:
    - aws ecr get-login-password --region=eu-central-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com
    - docker build --no-cache -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ah-frontend-repository:$CI_PIPELINE_IID ./frontend
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ah-frontend-repository:$CI_PIPELINE_IID
  rules:
      - changes:
          - frontend/**/*
  tags:
      - ci-shared

build-backend-image:
  stage: build
  image: docker:latest
  services:
      - docker:dind
  script:
    - aws ecr get-login-password --region=eu-central-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com
    - docker build --no-cache -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ah-backend:$CI_PIPELINE_IID ./backend
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/ah-backend:$CI_PIPELINE_IID
  rules:
      - changes:
          - backend/**/*
  tags:
      - ci-shared