apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vpcxrs.xrdgroup.org
spec:
  group: xrdgroup.org
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vpcName:
                  type: string
                subnetName:
                  type: string
                igwName:
                  type: string
              required:
                - vpcName
                - subnetName
                - igwName
          required:
            - spec
  names:
    kind: VPCXR
    plural: vpcxrs
  claimNames:
    kind: VPC
    plural: vpcs