apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vpc-composition
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/depends-on: "XRD/vpcxrs.xrdgroup.org"
spec:
  compositeTypeRef:
    apiVersion: xrdgroup.org/v1alpha1
    kind: VPCXR
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: patch-and-transform-function
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: vpc-patchset
            patches:
              - fromFieldPath: spec.vpcName
                toFieldPath: spec.forProvider.vpcIdRef.name
        resources:
#########################################################################################
          - name: vpc
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: VPC
              spec:
                forProvider:
                  cidrBlock: 10.0.0.0/16
                  region: eu-central-1
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.vpcName
                toFieldPath: metadata.name

#########################################################################################
          - name: subnet-1
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: Subnet
              spec:
                forProvider:
                  region: eu-central-1
                  availabilityZone: eu-central-1a
                  cidrBlock: 10.0.0.0/24
                  mapPublicIPOnLaunch: true
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.subnetName
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-1"
              - type: PatchSet
                patchSetName: vpc-patchset
#########################################################################################
          - name: subnet-2
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: Subnet
              spec:
                forProvider:
                  region: eu-central-1
                  availabilityZone: eu-central-1b
                  cidrBlock: 10.0.1.0/24
                  mapPublicIPOnLaunch: true
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.subnetName
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-2"
              - type: PatchSet
                patchSetName: vpc-patchset
#########################################################################################
          - name: internet-gateway
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: InternetGateway
              spec:
                forProvider:
                  region: eu-central-1
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - type: PatchSet
                patchSetName: vpc-patchset
              - fromFieldPath: spec.igwName
                toFieldPath: metadata.name
#########################################################################################
          - name: route-table
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: RouteTable
              metadata:
                name: ah-app-route-table
              spec:
                forProvider:
                  region: eu-central-1
                  routes:
                    - destinationCidrBlock: 0.0.0.0/0
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.igwName
                toFieldPath: spec.forProvider.routes[0].gatewayIdRef.name
              - type: PatchSet
                patchSetName: vpc-patchset
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.associations[0].subnetIdRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-1"
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.associations[1].subnetIdRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-2"
#########################################################################################
    - step: detect-readiness
      functionRef:
        name: auto-ready-function