apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
    targetRevision: main
    path: application_cluster/kubernetes/web_application/frontend
  destination:
    name: arn:aws:eks:eu-central-1:722377226063:cluster/ah-app-eks
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true