apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-composition
spec:
  compositeTypeRef:
    apiVersion: xrdgroup.org/v1alpha1
    kind: ClusterXR
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: patch-and-transform-function
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: node-role-patchset
            patches:
              - fromFieldPath: spec.nodeRoleName
                toFieldPath: spec.forProvider.roleNameRef.name
          - name: vpc-patchset
            patches:
              - fromFieldPath: spec.vpcName
                toFieldPath: spec.forProvider.vpcIdRef.name
        resources:
#########################################################################################
          - name: cluster-iam-role
            base:
              apiVersion: iam.aws.crossplane.io/v1beta1
              kind: Role
              spec:
                forProvider:
                  assumeRolePolicyDocument: |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Service": [
                              "eks.amazonaws.com"
                            ]
                          },
                          "Action": [
                            "sts:AssumeRole",
                            "sts:TagSession"
                          ]
                        }
                      ]
                    }
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.clusterRoleName
                toFieldPath: metadata.name
#########################################################################################
          - name: cluster-role-policy-attachment-AmazonEKSClusterPolicy
            base:
              apiVersion: iam.aws.crossplane.io/v1beta1
              kind: RolePolicyAttachment
              metadata:
                name: ah-app-cluster-role-policy-attachment-AmazonEKSClusterPolicy
              spec:
                forProvider:
                  policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
                  roleNameRef:
                    name: ah-app-cluster-role
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.clusterRoleName
                toFieldPath: spec.forProvider.roleNameRef.name
#########################################################################################
          - name: node-iam-role
            base:
              apiVersion: iam.aws.crossplane.io/v1beta1
              kind: Role
              metadata:
                name: ah-app-node-role
              spec:
                forProvider:
                  assumeRolePolicyDocument: |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Service": [
                              "ec2.amazonaws.com"
                            ]
                          },
                          "Action": [
                            "sts:AssumeRole"
                          ]
                        }
                      ]
                    }
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.nodeRoleName
                toFieldPath: metadata.name
#########################################################################################
          - name: node-role-policy-attachment-AmazonEKSWorkerNodePolicy
            base:
              apiVersion: iam.aws.crossplane.io/v1beta1
              kind: RolePolicyAttachment
              metadata:
                name: ah-app-node-role-policy-attachment-AmazonEKSWorkerNodePolicy
              spec:
                forProvider:
                  policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
                providerConfigRef:
                        name: aws-provider-config
            patches:
              - type: PatchSet
                patchSetName: node-role-patchset
#########################################################################################
          - name: node-role-policy-attachment-AmazonEC2ContainerRegistryReadOnly
            base:
              apiVersion: iam.aws.crossplane.io/v1beta1
              kind: RolePolicyAttachment
              metadata:
                name: ah-app-node-role-policy-attachment-AmazonEC2ContainerRegistryReadOnly
              spec:
                forProvider:
                  policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - type: PatchSet
                patchSetName: node-role-patchset
#########################################################################################
          - name: node-role-policy-attachment-AmazonEKS_CNI_Policy
            base:
              apiVersion: iam.aws.crossplane.io/v1beta1
              kind: RolePolicyAttachment
              metadata:
                name: ah-app-node-role-policy-attachment-AmazonEKS_CNI_Policy
              spec:
                forProvider:
                  policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - type: PatchSet
                patchSetName: node-role-patchset
#########################################################################################
          - name: vpc
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: VPC
              spec:
                forProvider:
                  cidrBlock: 10.0.0.0/16
                  region: eu-central-1
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.vpcName
                toFieldPath: metadata.name
#########################################################################################
          - name: subnet-1
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: Subnet
              spec:
                forProvider:
                  region: eu-central-1
                  availabilityZone: eu-central-1a
                  cidrBlock: 10.0.0.0/24
                  mapPublicIPOnLaunch: true
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.subnetName
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-1"
              - type: PatchSet
                patchSetName: vpc-patchset
#########################################################################################
          - name: subnet-2
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: Subnet
              spec:
                forProvider:
                  region: eu-central-1
                  availabilityZone: eu-central-1b
                  cidrBlock: 10.0.1.0/24
                  mapPublicIPOnLaunch: true
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.subnetName
                toFieldPath: metadata.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-2"
              - type: PatchSet
                patchSetName: vpc-patchset
#########################################################################################
          - name: eks-security-group
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: SecurityGroup
              spec:
                forProvider:
                  region: eu-central-1
                  description: Secutiry group for ah application cluster
                  egress:
                    - fromPort: -1
                      ipProtocol: "-1"
                      ipRanges:
                        - cidrIp: 0.0.0.0/0
                      toPort: -1
                  ingress:
                    - fromPort: -1
                      ipProtocol: "-1"
                      ipRanges:
                        - cidrIp: 0.0.0.0/0
                      toPort: -1
                  tags:
                    - key: cluster-name
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.securityGroupName
                toFieldPath: spec.forProvider.groupName
              - fromFieldPath: spec.securityGroupName
                toFieldPath: metadata.name
              - type: PatchSet
                patchSetName: vpc-patchset
              - fromFieldPath: spec.clusterName
                toFieldPath: spec.forProvider.tags[0].value
#########################################################################################
          - name: internet-gateway
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: InternetGateway
              spec:
                forProvider:
                  region: eu-central-1
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - type: PatchSet
                patchSetName: vpc-patchset
              - fromFieldPath: spec.igwName
                toFieldPath: metadata.name
#########################################################################################
          - name: route-table
            base:
              apiVersion: ec2.aws.crossplane.io/v1beta1
              kind: RouteTable
              metadata:
                name: ah-app-route-table
              spec:
                forProvider:
                  region: eu-central-1
                  routes:
                    - destinationCidrBlock: 0.0.0.0/0
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.igwName
                toFieldPath: spec.forProvider.routes[0].gatewayIdRef.name
              - type: PatchSet
                patchSetName: vpc-patchset
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.associations[0].subnetIdRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-1"
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.associations[1].subnetIdRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-2"
#########################################################################################
          - name: eks-cluster
            base:
              apiVersion: eks.aws.crossplane.io/v1beta1
              kind: Cluster
              spec:
                forProvider:
                  region: eu-central-1
                  resourcesVpcConfig:
                    endpointPrivateAccess: true
                    endpointPublicAccess: true
                  roleArnRef:
                    name: ah-app-cluster-role
                  version: "1.31"
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.clusterRoleName
                toFieldPath: spec.forProvider.roleArnRef.name
              - fromFieldPath: spec.clusterName
                toFieldPath: metadata.name
              - fromFieldPath: spec.securityGroupName
                toFieldPath: spec.forProvider.resourcesVpcConfig.securityGroupIdRefs[0].name
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.resourcesVpcConfig.subnetIdRefs[0].name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-1"
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.resourcesVpcConfig.subnetIdRefs[1].name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-2"
#########################################################################################
          - name: node-group
            base:
              apiVersion: eks.aws.crossplane.io/v1alpha1
              kind: NodeGroup
              metadata:
                name: ah-app-eks-node-group
              spec:
                forProvider:
                  region: eu-central-1
                  instanceTypes:
                    - "t3.small"
                  scalingConfig:
                    desiredSize: 2
                    maxSize: 2
                    minSize: 2
                  updateConfig:
                    force: true
                    maxUnavailablePercentage: 50
                providerConfigRef:
                  name: aws-provider-config
            patches:
              - fromFieldPath: spec.clusterName
                toFieldPath: spec.forProvider.clusterNameRef.name
              - fromFieldPath: spec.nodeRoleName
                toFieldPath: spec.forProvider.nodeRoleRef.name
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.subnetRefs[0].name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-1"
              - fromFieldPath: spec.subnetName
                toFieldPath: spec.forProvider.subnetRefs[1].name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-2"
#########################################################################################
    - step: detect-readiness
      functionRef:
        name: auto-ready-function
