apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: infrastructure_cluster/crossplane/cluster
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: infrastructure_cluster/kubernetes/infrastructure
      directory:
        include: "EKSCluster.yaml"
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true