apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-configuration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: infrastructure_cluster/crossplane/vpc
    - repoURL: https://gitlab.itgix.com/elsys/alexander-hristov/infrastructure
      targetRevision: main
      path: infrastructure_cluster/kubernetes/infrastructure/VPC
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - ApplyOutOfSyncOnly=true
