apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/aws/eks-charts"
    path: "stable/aws-load-balancer-controller"
    helm:
      values: |
        clusterName: ah-app-eks
        serviceAccount:
          create: false
          name: alb-controller-sa
  destination:
    name: arn:aws:eks:eu-central-1:722377226063:cluster/ah-app-eks
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true