apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ecrrepositoryxrs.xrdgroup.org
spec:
  group: xrdgroup.org
  versions:
    - name: v1alpha1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                frontendRepositoryName:
                  type: string
                backendRepositoryName:
                  type: string
              required:
                - frontendRepositoryName
                - backendRepositoryName
          required:
            - spec
  names:
    kind: ECRRepositoryXR
    plural: ecrrepositoryxrs
  claimNames:
    kind: ECRRepository
    plural: ecrrepositories